/* Generated by scripts/build-graph.mjs — do not edit by hand. */

export const GRAPH_STATS = {
  buildId: '1y3fr',
  notes: 948,
  courses: 32,
  links: 6876,
  indexSlug: 'computer-science',
} as const;
